[colors]
ansi = [
  "#282c34",
  "#e06c75",
  "#98c379",
  "#e5c07b",
  "#61afef",
  "#c678dd",
  "#56b6c2",
  "#abb2bf",
]
brights = [
  "#5c6370",
  "#e9969d",
  "#b3d39c",
  "#edd4a6",
  "#8fc6f4",
  "#d7a1e7",
  "#7bc6d0",
  "#c8cdd5",
]
background = "#282c34"
foreground = "#abb2bf"
cursor_bg = "#abb2bf"
cursor_fg = "#282c34"
cursor_border = "#abb2bf"
selection_bg = "#5c6370"

[colors.tab_bar]
background = "#181a1f"

[colors.tab_bar.active_tab]
bg_color = "#282c34"
fg_color = "#abb2bf"

[colors.tab_bar.inactive_tab]
bg_color = "#21252b"
fg_color = "#5c6370"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#21252b"
fg_color = "#848b98"

[colors.tab_bar.new_tab]
bg_color = "#181a1f"
fg_color = "#848b98"

[colors.tab_bar.new_tab_hover]
bg_color = "#181a1f"
fg_color = "#848b98"
intensity = "Bold"

[colors.indexed]

[metadata]
name = "onedarkpro"
origin_url = "https://github.com/olimorris/onedarkpro.nvim"

